# Generated by Django 3.1 on 2022-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_offer',
            field=models.IntegerField(),
        ),
    ]
